# Generated by Django 5.0.2 on 2024-02-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePsPFailedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('failed_transaction_code', models.CharField(max_length=8)),
                ('band_code', models.CharField(max_length=25)),
                ('volume_of_transactions', models.PositiveIntegerField()),
                ('value_of_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_of_failed_transactions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BasePspCustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_code', models.CharField(max_length=10)),
                ('request_id', models.CharField(blank=True, max_length=10)),
                ('is_attached', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('reporting_date', models.DateField()),
            ],
            options={
                'unique_together': {('institution_code', 'reporting_date')},
            },
        ),
        migrations.CreateModel(
            name='MobilePspCustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('sub_country_code', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_code', models.CharField(max_length=10)),
                ('wallet_code', models.CharField(max_length=3)),
                ('no_of_customers_registered', models.PositiveIntegerField()),
                ('no_of_customers_active', models.PositiveIntegerField()),
                ('no_of_customers_inactive', models.PositiveIntegerField()),
                ('no_of_customers_dormant', models.PositiveIntegerField()),
                ('balances_in_customer_accts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_of_transactions', models.PositiveIntegerField()),
                ('value_of_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.basepspcustomerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePsPCustomerTransactionCategorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('sub_country_code', models.CharField(max_length=4)),
                ('band_code', models.CharField(max_length=25)),
                ('volume_of_transactions', models.PositiveIntegerField()),
                ('value_of_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.basepspcustomerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePsPInteroperability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('band_code', models.CharField(max_length=25)),
                ('incoming_transaction_volume', models.PositiveIntegerField()),
                ('incoming_transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outgoing_transaction_volume', models.PositiveIntegerField()),
                ('outgoing_transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.basepspcustomerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePspMerchantCustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('sub_country_code', models.CharField(max_length=4)),
                ('band_code', models.CharField(max_length=25)),
                ('merchant_id', models.CharField(max_length=10)),
                ('merchant_type_code', models.CharField(max_length=10)),
                ('merchant_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('merchant_classification_code', models.CharField(max_length=10)),
                ('merchant_status', models.CharField(max_length=25)),
                ('number_of_customers', models.PositiveIntegerField()),
                ('end_of_day_balances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.basepspcustomerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePspMerchantTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('psp_id', models.CharField(max_length=10)),
                ('reporting_date', models.DateField()),
                ('sub_country_code', models.CharField(max_length=4)),
                ('band_code', models.CharField(max_length=25)),
                ('merchant_id', models.CharField(max_length=10)),
                ('merchant_type_code', models.CharField(max_length=10)),
                ('merchant_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('merchant_classification_code', models.CharField(max_length=10)),
                ('merchant_status', models.CharField(max_length=25)),
                ('volume_of_deposit_transactions', models.PositiveIntegerField()),
                ('value_of_deposit_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_withdrawal_transactions', models.PositiveIntegerField()),
                ('value_of_withdrawal_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.basepspcustomerinfo')),
            ],
        ),
    ]
